### ISSUE TITLE
Request to use some of your applications for a workshop

### ISSUE THREAD

**Issue by qmatteoq** [jbe2277/musicmanager#2]
Hello and sorry for using GitHub issues to submit such a request, but I couldn't find a way to contact you directly.
I work in Microsoft in the Windows AppConsult team and, as part of the BUILD activities, I'm running on 9th May in Seattle a workshop about Windows apps modernization.
During the day the participants will explore how to start from a classic WPF application and modernize it using .NET Core 3.0, XAML Islands, UWP and MSIX.

I was searching for open source applications that could be used as a starting point for the 2nd part of the workshop and I stumbled across Music Manager and DotNetPad, which look like the perfect candidate. You have published them with the MIT license so, from a legal point of view, there shouldn't be any problem. However, I wanted to double check with you if you're ok with this and, if eventually, you would be interested in the workshop outcome.

Thanks!

**Comment by jbe2277** [comment]
Thank you for the interest. You are welcome to use any of my open source applications in your workshops. It would be great if you could update me about the workshop outcome.

Maybe you are interested in my WAF reference sample applications which I have ported to .NET Core 3.0: https://github.com/jbe2277/waf/tree/netcoreapp3.0 (Please check out the netcoreapp3.0 branch). The BookLibrary and InformationManager work great but the Writer application has still some issues which I have reported at https://github.com/dotnet/wpf.

**Comment by qmatteoq** [comment]
Thanks a lot! I'll make sure to quote you during the workshop and I'll get back with the outcome!
